### ISSUE TITLE
Changing zoom level alters spacing between lines

### ISSUE THREAD

**Issue by druskus20** [kognise/obsidian-atom#13]
When changing the zoom level, the space between the lines is also altered, as can be seen in the following image: 
![obsidian](https://user-images.githubusercontent.com/43417195/137801154-dba1dcd0-e385-4e6a-832a-063087dc044f.png)
I've seemed to have narrowed down the issue to the following property on `<p>`: 

```css
.markdown-preview-view.is-readable-line-width .markdown-preview-section, .markdown-source-view.is-readable-line-width .CodeMirror {
    max-width: 900px !important;
    line-height: 26px;
}
```
Disabling `line-height` seems to fix the issue.
