### ISSUE TITLE
Folder name line offset

### ISSUE THREAD

**Issue by SBmarOG** [kognise/obsidian-atom#22]
The vertical lines in the folder navigation are a bit to far on the left, not directly below the arrow to fold it together.

**Like you can see here on the screenshot:**
https://i.imgur.com/3HrZWln.png

Also I added this to my custom CSS snipped to add a little space between the folder name and the arrorow:
```CSS
.nav-folder-title-content
{
  padding-left: 4px;
}
```

Maybe this helps to improve your ATOM theme for Obsidian.
