### ISSUE TITLE
Fav Menu Icon and Text (starred menu)

### ISSUE THREAD

**Issue by SBmarOG** [kognise/obsidian-atom#24]
I added this code to a custom css file:
```CSS
/* OBSIDIAN GUI --------------------------------------------------------------- */
.workspace-leaf-content[data-type="starred"] .item-list .nav-file-icon
{
  position: relative;
  top: 1px;
}

.workspace-leaf-content[data-type="starred"] .item-list .nav-file-title-content
{
  position: relative;
  top: -2px;
}
```

**This will fix it like this:**
https://imgur.com/a/psoi7kl

( 1 ) is default Atom Theme which have a styling issue for the favourites menu.
( 2 ) is my CSS-Fix for Atom Theme

Please implement this fix to the default Atom Theme for everyone.
