### ISSUE TITLE
Different color for heading

### ISSUE THREAD

**Issue by shriar** [kognise/obsidian-atom#28]
If there is different color for different heading then notes will be more readable.

**Comment by jose-elias-alvarez** [comment]
I'd love to see this included in the theme, either as a default or as an option, but in the meantime it's pretty easy to solve this with [CSS snippets](https://help.obsidian.md/Extending+Obsidian/CSS+snippets) using the variables defined [here](https://github.com/kognise/obsidian-atom/blob/master/obsidian.css):

```css
/* just an example, use whichever colors / levels you like */
.cm-header-3 {
  color: var(--yellow);
}
.cm-header-4 {
  color: var(--red);
}
.cm-header-5 {
  color: var(--green);
}
.cm-header-6 {
  color: var(--orange);
}
```
