### ISSUE TITLE
Start of note titles cut off in nav file titles

### ISSUE THREAD

**Issue by mikeu** [kognise/obsidian-atom#4]
Thanks for this great theme! I've been using it for a few weeks now and am very happy with all but one minor issue. The beginning of every note title in the nav tab is missing:
![image](https://user-images.githubusercontent.com/605493/102915358-e96fa000-443e-11eb-9eca-2a01bdbdf671.png)
Those dates should obviously start with a complete "2", and the entire "T" is missing from "Template", as well as a pixel or two of the "e".

The problem seems to be a combination of the base style
```css
.nav-file-title-content {
    text-indent: -10px;
}
```
and the theme style
```css
.nav-file-title-content {
    overflow: hidden;
}
```

Note that nav _folder_ titles do appear correctly. As far as I can tell, this is because they don't have the base `text-indent: -10px`, so the theme's `overflow: hidden` isn't causing a problem.
